name: Auto Update

on:
    workflow_dispatch:
    schedule:
        -   cron: '0 0 1 * *'

defaults:
    run:
        shell: bash

jobs:
    auto-update:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    ssh-key: ${{ secrets.SSH_KEY_PRIVATE }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: 'none'
                    extensions: 'json,xml,xsl'
                    ini-values: 'memory_limit=-1'
                    php-version: '8.2'
                    tools: pecl

            -   name: Display versions
                run: |
                    php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
                    php -i

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: 8.0-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        8.0-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Get Lucide version
                run: echo "lucide_version=$(curl -s https://api.github.com/repos/lucide-icons/lucide/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV

            -   name: Init git submodule
                run: git submodule init

            -   name: Update git submodule
                run: git submodule update

            -   name: Checkout latest version
                run: git -C lucide checkout "${{ env.lucide_version }}"

            -   name: Build files
                run: composer run-script build

            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v3
                with:
                    commit-message: "Update resources from Lucide ${{ env.lucide_version }}"
                    branch: automated/lucide-update
                    delete-branch: true
                    title: "[AUTO] Lucide Update ${{ env.lucide_version }}"
                    body: |
                        Updated resources built based on Lucide ${{ env.lucide_version }}
                    labels: automated pr
                    assignees: |
                        natewiebe13

            -   name: Check outputs
                run: |
                    echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
                    echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
